version: "3"
services:
    palworld:
        ports:
          - "8211:8211"
          - "8211:8211/udp"
          - "25575:25575"
          - "25575:25575/udp"
        container_name: steamcmd_palworld
        image: miaowmint/palworld
        volumes:
          - palworld_server:/home/steam/Steam/steamapps/common/PalServer
        restart: unless-stopped

    palword_manager:
      image: palworld_server_manager
      ports:
        - "18080:8080"
      container_name: palword_manager
      environment:
        - DEFAULT_USER=palworld
        - WEB_PORT=8080
        - DB_ENGINE=sqlite
      volumes:
        - palworld_server:/code/data/palworld
        - /var/run/docker.sock:/var/run/docker.sock
      restart: unless-stopped

volumes:
  palworld_server:
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /data/pal_manage